return {
	BackgroundColor = Color3.fromRGB(46, 46, 46),
	BackgroundTransparency = 0.05,
	BackgroundCornerRadius = UDim.new(0, 8),
	TextActiveColor = Color3.fromRGB(240, 240, 240),
	TextDescriptiveColor = Color3.fromRGB(178, 178, 178),
	TextErrorColor = Color3.fromRGB(255, 100, 100),
	TextFontRegular = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular),
	TextFontBold = Font.new("rbxassetid://12187365364", Enum.FontWeight.SemiBold),
	StrokeThickness = 1,
	StrokeActiveColor = Color3.fromRGB(240, 240, 240),
	StrokeInactiveColor = Color3.fromRGB(178, 178, 178),
	StrokeErrorColor = Color3.fromRGB(255, 100, 100),
}
