return {
    BackgroundColor = Color3.fromRGB(30, 30, 46),
	BackgroundTransparency = 0,
	BackgroundCornerRadius = UDim.new(0, 12),
	TextActiveColor = Color3.fromRGB(204, 167, 247),
	TextDescriptiveColor = Color3.fromRGB(127, 132, 156),
	TextErrorColor = Color3.fromRGB(215, 130, 156),
	TextFontRegular = Font.fromName("Inconsolata", Enum.FontWeight.Regular),
    TextFontBold = Font.fromName("Inconsolata", Enum.FontWeight.SemiBold),
	StrokeThickness = 2,
	StrokeActiveColor = Color3.fromRGB(204, 167, 247),
	StrokeInactiveColor = Color3.fromRGB(127, 132, 156),
	StrokeErrorColor = Color3.fromRGB(215, 130, 156),
}