return {
    BackgroundColor = Color3.fromRGB(12, 0, 32),
	BackgroundTransparency = 0,
	BackgroundCornerRadius = UDim.new(0, 12),
	TextActiveColor = Color3.fromRGB(172, 94, 245),
	TextDescriptiveColor = Color3.fromRGB(174, 143, 230),
	TextErrorColor = Color3.fromRGB(253, 68, 69),
	TextFontRegular = Font.fromName("Inconsolata", Enum.FontWeight.Regular),
    TextFontBold = Font.fromName("Inconsolata", Enum.FontWeight.SemiBold),
	StrokeThickness = 1,
	StrokeActiveColor = Color3.fromRGB(172, 94, 245),
	StrokeInactiveColor = Color3.fromRGB(174, 143, 230),
	StrokeErrorColor = Color3.fromRGB(253, 68, 69),
}